AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  TaskAbstractGetContent:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.6
      Handler: GetContent.lambda_handler
      CodeUri: s3://task-abstract/0f64858133f0950909f1b75414e09b79
      MemorySize: 128
      Timeout: 3
  TaskAbstractGetProfile:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.6
      Handler: GetProfile.lambda_handler
      CodeUri: s3://task-abstract/0f64858133f0950909f1b75414e09b79
      MemorySize: 128
      Timeout: 3
  TaskAbstractGetJobs:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.6
      Handler: GetJobs.lambda_handler
      CodeUri: s3://task-abstract/0f64858133f0950909f1b75414e09b79
      MemorySize: 128
      Timeout: 3
